travis:
  secure:
    BINSTAR_TOKEN: sUoYAw7lvyQFaueQfkrIw8NY5HnO0WdPCQ7TDr6Ppu7l9qiJPNf4RTxvikYgXAZ3AW4ju2TIGc8P6/JWCbDzLYXt0k3nba7MXUOP/hXrzMHRRMR7QAgQBEGXA5hocq0Cxlg98YtQwjuv6t2Q808e1O5s2395NXqDbjXyqvlDGOCbpo9BR4+LDqgx02tRGEf8OL51yHz8dJe8XAe228F0goZE2C+biE/oLkwWmhwLERz1o3qVNZRq3ZhiULEv/VACKGE2mLt25I6g8LLQDPwbDIkv3P1tbdwzjhGKim0b7lRb6lhTkDPe8K0liz/xfgu+t48aVfxOErcqfR56uPorGhVEHhux+t1Q05lY2EVeMUt1whajBKYX28eJIsz0mnd9rrVWQM0+jVC6L7ni8WAa0h9npTIwJn6R5mUOuDwPfGLegUEL6oBafVHadeI+Oz9k7hQXWK/xBDGe4ygGc7Z+6MpOhb/qw++rAWjj/cSaUCkw1+kOXiH8bo2KSFxYNkfA3UWqNpb4r0EM3IFdBo2LbKUXajBs72xlLTALjG4NFnn+VkOwKRAo+kRlhZLbx4D1i710QH9PrV0HCuEDeyKFWzxjCUZDvCJTPIpFtijz7RL/PP42pQiKJssIsKsS9NHNcO6lVAWdDGOkWXpYqOfs6Kmwwug74j2siQvH9JyFk44=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
