travis:
  secure:
    BINSTAR_TOKEN: beqQOVBO6Ak+dPybb4yuteuPVLIu27xWgNOMJJP2so9UkmMza6A9tXGChr9dLbbGEhwJFiUaoWvJosa8wedcP1FRsLDb9Fkmjz4H1NzAimA6yfV1xbuWpWgNCShuP92BvNGVMNw7MnVLoIi7ho5hPzBMWQoqe+kvaq9jpW3LRV2QftmWtJRxgsmRaAsc86ghCReEdsTN14Rhmif3lP4vQEH+C11JwNniIbjd0Abz9sMQRDQj4hddgiPZ1LpHgJQFicMMS3aQkH8fpTrVR1fETegbToaTTJnCYdEac5KZ+tkyuKa+GsDUEB1kgKUKS0uFp/hutoqJdMrjpuQQXLbpgSk/M3BQjUVvsriJXlrnwOc0kcVeQzr82sOWgcPpI7m9aMI3ry+GIEd9DA/g2ctsF3ycbmezZBAESbzoO8m8lISzKLh8BsmQSQT5y3bYyjPPgGjLiNiWtsOERZukb/nVKfJ8D4V/rg2GxHSm1ddyD51zk5wZck4wIbJ96ZENd686LYuDixYVQXN/tAC8eWro2NrSRYUZd3IYlo8x+x9XX+sd/xvb12MVLqYJJN5mjychWUx7o2Y8+T/TPParC5uSHzz01DVnehAVXqj/iXUk7YFHnzFXjAT8VD4PSUPwh1KLV26qbtzkjut2TbRsfYqm0GGaV5fEONr3UTqU2nq+R5o=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
